resolver: nightly-2017-12-14
extra-package-dbs: []

flags:
  hakyll:
    previewServer: True
    watchServer:   True
    checkExternal: True

packages:
  - '.'

extra-deps:
  - hslua-module-text-0.1.2
  - skylighting-0.5

nix:
  enable: false
  packages:
    - zlib
