resolver: lts-11.7
extra-package-dbs: []
save-hackage-creds: false

flags:
  hakyll:
    previewServer: true
    watchServer:   true
    checkExternal: true
    usePandoc:     true
    buildWebsite:  true

packages:
  - '.'

nix:
  enable: false
  packages:
    - zlib

build:
  haddock: true
  haddock-hyperlink-source: true
  haddock-deps: false

extra-deps:
- 'pandoc-2.2'
- 'pandoc-types-1.17.4.2'
- 'pandoc-citeproc-0.14.3.1'
- 'tasty-1.1.0.1'
- 'fsnotify-0.3.0.0'
