resolver: nightly-2017-06-19
extra-package-dbs: []
extra-deps:
- 'optparse-applicative-0.14.0.0'
- 'pandoc-citeproc-0.10.5.1'
- 'QuickCheck-2.10.0.1'
- 'tasty-quickcheck-0.9'

flags:
  hakyll:
    previewServer: True
    watchServer:   True
    checkExternal: True

packages:
  - '.'

nix:
  enable: false
  packages:
    - zlib
