resolver: lts-12.14
compiler: ghc-8.4.2
save-hackage-creds: false

flags:
  hakyll:
    previewServer: true
    watchServer:   true
    checkExternal: true
    usePandoc:     true
    buildWebsite:  true

packages:
  - '.'

nix:
  enable: false
  packages:
    - zlib

build:
  haddock: true
  haddock-hyperlink-source: true
  haddock-deps: false

extra-deps:
- 'pandoc-2.4'
- 'pandoc-citeproc-0.15'
- 'yaml-0.11.0.0'

- 'libyaml-0.1.0.0'
- 'HsYAML-0.1.1.2'
- 'haddock-library-1.7.0'
- 'hslua-1.0.1'
- 'hslua-module-text-0.2.0'
