resolver: 'lts-19.17'
save-hackage-creds: false
system-ghc: true
skip-ghc-check: true

flags:
  hakyll:
    previewServer: true
    watchServer:   true
    checkExternal: true
    usePandoc:     true
    buildWebsite:  true

packages:
  - '.'

nix:
  packages:
    - openssh  # for deployment
    - rsync    # for deployment
    - zlib

extra-deps:
