resolver: lts-13.0
save-hackage-creds: false

flags:
  hakyll:
    previewServer: true
    watchServer:   true
    checkExternal: true
    usePandoc:     true
    buildWebsite:  true

packages:
  - '.'

nix:
  enable: false
  packages:
    - zlib

build:
  haddock: true
  haddock-hyperlink-source: true
  haddock-deps: false

extra-deps:
- 'ipynb-0.1'
- 'lrucache-1.2.0.1'
- 'pandoc-2.7'
- 'pandoc-citeproc-0.16.2'
- 'skylighting-0.7.7'
- 'skylighting-core-0.7.7'
- 'texmath-0.11.2.2'
