resolver: nightly-2018-01-15
extra-package-dbs: []

flags:
  hakyll:
    previewServer: True
    watchServer:   True
    checkExternal: True
    buildWebsite:  True

packages:
  - '.'

allow-newer: True

extra-deps:
  - 'binary-0.9.0.0'
  - 'http-types-0.11'
  - 'pandoc-2.1'
  - 'pandoc-citeproc-0.13'
  - 'QuickCheck-2.11.3'
  - 'tasty-1.0.0.1'
  - 'tasty-hunit-0.10.0.1'

nix:
  enable: false
  packages:
    - zlib
