resolver: lts-16.9
save-hackage-creds: false

flags:
  hakyll:
    previewServer: true
    watchServer:   true
    checkExternal: true
    usePandoc:     true
    buildWebsite:  true

packages:
  - '.'

nix:
  enable: false
  packages:
    - zlib

build:
  haddock: true
  haddock-hyperlink-source: true
  haddock-deps: false

extra-deps:
- 'commonmark-0.1.0.2'
- 'commonmark-extensions-0.2.0.1'
- 'commonmark-pandoc-0.2.0.1'
- 'hslua-1.1.2'
- 'jira-wiki-markup-1.3.2'
- 'pandoc-2.10.1'
- 'pandoc-types-1.21'
