resolver: nightly-2017-11-20
extra-package-dbs: []
extra-deps: []

flags:
  hakyll:
    previewServer: True
    watchServer:   True
    checkExternal: True

packages:
  - '.'

nix:
  enable: false
  packages:
    - zlib
