resolver: lts-11.0
extra-package-dbs: []

flags:
  hakyll:
    previewServer: True
    watchServer:   True
    checkExternal: True
    usePandoc:     True
    buildWebsite:  True

packages:
  - '.'

extra-deps: []

nix:
  enable: false
  packages:
    - zlib
