resolver: 'lts-22.23' # If you change this, please update GHC version "stack / ghc" job in .github/workflows/main.yaml
save-hackage-creds: false
system-ghc: true
skip-ghc-check: true

flags:
  hakyll:
    previewServer: true
    watchServer:   true
    checkExternal: true
    usePandoc:     true
    buildWebsite:  true

packages:
  - '.'

nix:
  packages:
    - openssh  # for deployment
    - rsync    # for deployment
    - zlib
    - pkgconfig

extra-deps:
