resolver: nightly-2018-08-29
save-hackage-creds: false

flags:
  hakyll:
    previewServer: true
    watchServer:   true
    checkExternal: true
    usePandoc:     true
    buildWebsite:  true

packages:
  - '.'

nix:
  enable: false
  packages:
    - zlib

build:
  haddock: true
  haddock-hyperlink-source: true
  haddock-deps: false

extra-deps:
- file-embed-0.0.11
- QuickCheck-2.12.4
- yaml-0.10.1.1

- pandoc-2.2.3.2
- pandoc-citeproc-0.14.3.1
- HsYAML-0.1.1.2
- aeson-1.3.1.1
- rfc5051-0.1.0.3
