version: 2
jobs:
  build:
    docker:
      - image: 'fpco/stack-build:latest'
    steps:
      - checkout
      - restore_cache:
          key: 'v1-hakyll-{{ arch }}-{{ .Branch }}'
      - run:
          name: 'Update cabal indices'
          command: 'cabal update'
      - run:
          name: 'Install dependencies'
          command: '.circleci/tickle.sh cabal install --only-dependencies --enable-tests --jobs=1'
      - run:
          name: 'Build and run tests'
          command: 'cabal test'
      - save_cache:
          key: 'v1-hakyll-{{ arch }}-{{ .Branch }}-{{ .Revision }}'
          paths:
            - '~/.cabal'
            - '~/.ghc'
